services:


  api:
    build:
      context: .
      dockerfile: AdvancedTodoServer.WebAPI/Dockerfile
    image: advanced-todo-server
    container_name: AdvancedTodoServer
    ports:
      - 54010:8080